pluginManagement {
    repositories {
        maven {
            url 'https://plugins.gradle.org/m2/'
        }
        mavenCentral()
    }
}

rootProject.name = 'attach-extended'

include 'log'
include 'file-import'

project(':log').projectDir                     = file('modules/log')
project(':file-import').projectDir             = file('modules/file-import')